import { ArrowLeft } from "lucide-react";
import Link from "next/link";
import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "Terms of Service — ProposalAI",
  description: "ProposalAI terms of service — rules and guidelines for using our platform.",
};

export default function TermsOfServicePage() {
  return (
    <div className="min-h-screen bg-white">
      <div className="max-w-3xl mx-auto px-4 sm:px-6 py-12">
        <Link href="/" className="inline-flex items-center gap-2 text-sm text-slate-500 hover:text-slate-700 mb-8">
          <ArrowLeft className="w-4 h-4" /> Back to Home
        </Link>

        <h1 className="text-3xl font-bold text-slate-900 mb-2">Terms of Service</h1>
        <p className="text-sm text-slate-400 mb-10">Last updated: February 2026</p>

        <div className="prose prose-slate max-w-none space-y-6 text-slate-600 leading-relaxed">
          <section>
            <h2 className="text-xl font-semibold text-slate-900 mt-8 mb-3">1. Acceptance of Terms</h2>
            <p>By accessing or using ProposalAI ("the Service"), you agree to be bound by these Terms of Service. If you do not agree, please do not use the Service.</p>
          </section>

          <section>
            <h2 className="text-xl font-semibold text-slate-900 mt-8 mb-3">2. Description of Service</h2>
            <p>ProposalAI is a SaaS platform that helps freelancers create AI-powered proposals, track client engagement, and manage invoicing. The Service includes proposal generation, client management, invoicing, and related features.</p>
          </section>

          <section>
            <h2 className="text-xl font-semibold text-slate-900 mt-8 mb-3">3. Account Registration</h2>
            <p>You must provide accurate and complete information when creating an account. You are responsible for maintaining the security of your account credentials and for all activities that occur under your account.</p>
          </section>

          <section>
            <h2 className="text-xl font-semibold text-slate-900 mt-8 mb-3">4. Subscription & Billing</h2>
            <p>ProposalAI offers free and paid subscription plans. Paid subscriptions are billed through Paddle, our payment processor. You may cancel your subscription at any time; access continues until the end of the current billing period. Refunds are handled on a case-by-case basis.</p>
          </section>

          <section>
            <h2 className="text-xl font-semibold text-slate-900 mt-8 mb-3">5. AI-Generated Content</h2>
            <p>Proposals generated by our AI are provided as drafts and suggestions. You are responsible for reviewing, editing, and finalizing all content before sending it to clients. ProposalAI does not guarantee the accuracy, completeness, or suitability of AI-generated content.</p>
          </section>

          <section>
            <h2 className="text-xl font-semibold text-slate-900 mt-8 mb-3">6. Your Content</h2>
            <p>You retain ownership of all content you create using ProposalAI, including proposals, invoices, and client data. By using the Service, you grant us a limited license to store, process, and display your content as needed to provide the Service.</p>
          </section>

          <section>
            <h2 className="text-xl font-semibold text-slate-900 mt-8 mb-3">7. Acceptable Use</h2>
            <p>You agree not to use the Service for any illegal or unauthorized purpose, to distribute malware or harmful content, to attempt to gain unauthorized access to other accounts, or to abuse the AI generation system beyond reasonable usage.</p>
          </section>

          <section>
            <h2 className="text-xl font-semibold text-slate-900 mt-8 mb-3">8. Limitation of Liability</h2>
            <p>ProposalAI is provided "as is" without warranties of any kind. We are not liable for any indirect, incidental, or consequential damages arising from your use of the Service, including but not limited to lost revenue, lost data, or business interruption.</p>
          </section>

          <section>
            <h2 className="text-xl font-semibold text-slate-900 mt-8 mb-3">9. Termination</h2>
            <p>We reserve the right to suspend or terminate your account for violations of these Terms. You may delete your account at any time through your account settings.</p>
          </section>

          <section>
            <h2 className="text-xl font-semibold text-slate-900 mt-8 mb-3">10. Changes to Terms</h2>
            <p>We may update these Terms from time to time. Continued use of the Service after changes constitutes acceptance of the updated Terms.</p>
          </section>

          <section>
            <h2 className="text-xl font-semibold text-slate-900 mt-8 mb-3">11. Contact</h2>
            <p>For questions about these Terms, contact us at <a href="mailto:support@proposalai.app" className="text-emerald-600 hover:underline">support@proposalai.app</a>.</p>
          </section>
        </div>
      </div>
    </div>
  );
}
